---
project_root: "/home/{{ ansible_user }}/app"
env_type: "development"
service_name: "all"

enable_monitoring: false

updatable_services:
  - frontend
  - backend

supported_env_types:
  - development
  - staging

env_files:
  - { src: "backend.env.j2", dest: "backend.env" }
  - { src: "database.env.j2", dest: "database.env" }
