services:
  frontend:
    image: whatislavx/wdoc-frontend:latest
    env_file: frontend.env
    depends_on:
      - backend
    restart: always
    networks:
      - wdoc-network

  backend:
    image: whatislavx/wdoc-backend:latest
    env_file: backend.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    networks:
      - wdoc-network

  db:
    image: postgres:15-alpine
    container_name: wdoc-db
    restart: always
    env_file:
      - database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wdoc-network


  nginx:
    image: nginx:stable-alpine
    container_name: wdoc-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-development.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - wdoc-network

networks:
  wdoc-network:
    driver: bridge

volumes:
  postgres_data: