output "certificate_arn" {
  value       = aws_acm_certificate.this.arn
  description = "The ARN of the created ACM certificate."
}

output "domain_validation_options" {
  value       = aws_acm_certificate.this.domain_validation_options
  description = "The raw DNS validation records generated by ACM."
}
