---
- name: "FS: Project directory"
  ansible.builtin.file:
    path: "{{ project_root }}"
    state: directory
    owner: wdoc_ansible_user
    group: wdoc_ansible_user
    mode: "0755"

- name: "Configs: Deployment files"
  block:
    - name: "Render environment files"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ project_root }}/{{ item.dest }}"
        owner: wdoc_ansible_user
        group: wdoc_ansible_user
        mode: "0644"
      loop: "{{ env_files }}"

    - name: "Copy infrastructure configs"
      ansible.builtin.copy:
        src: "../{{ item }}-{{ env_type }}.{{ 'yml' if item == 'docker-compose' else
          'conf' }}"
        dest: "{{ project_root }}/{{ 'docker-compose.yml' if item == 'docker-compose'
          else 'nginx.conf' }}"
        owner: wdoc_ansible_user
        group: wdoc_ansible_user
        mode: "0644"
      loop: [ "docker-compose", "nginx" ]

- name: "Deploy: Docker Compose"
  block:
    - name: "Docker: Capture state"
      ansible.builtin.shell: "docker compose ps -q"
      args:
        chdir: "{{ project_root }}"
      register: current_containers
      changed_when: false
      failed_when: false

    - name: "Docker: Capture images for rollback"
      ansible.builtin.shell: "docker compose ps -q | xargs -I {} docker inspect
        --format '{{ '{{.Name}}:{{.Image}}' }}' {}"
      args:
        chdir: "{{ project_root }}"
      register: pre_deploy_state
      when: current_containers.stdout != ""
      changed_when: false
      failed_when: false

    - name: "Docker: Pull and Up (Wait for Health)"
      ansible.builtin.shell: |
        docker compose pull
        # Додано --wait для контролю healthcheck
        docker compose up -d --remove-orphans --wait --wait-timeout 300
      args:
        chdir: "{{ project_root }}"

  rescue:
    - name: "Rollback: Cleanup on first deploy failure"
      ansible.builtin.shell: "docker compose down"
      args:
        chdir: "{{ project_root }}"
      when: current_containers.stdout == ""

    - name: "Rollback: Revert to previous stable state"
      ansible.builtin.shell: "docker compose up -d"
      args:
        chdir: "{{ project_root }}"
      when: current_containers.stdout != ""

    - name: "Rollback: Fail deployment"
      ansible.builtin.fail:
        msg: "Deployment failed healthchecks. System cleaned up or rolled back."
