- name: App Deploy
  hosts: "{{ env_type }}"
  become: yes

  vars:
    project_root: "/home/{{ ansible_user }}/app"

  tasks:
    - name: Deploy env files
      template:
        src: "templates/{{ item.src }}"
        dest: "{{ project_root }}/{{ item.dest }}"
        mode: "0600"
      loop:
        - { src: "frontend.env.j2", dest: "frontend.env" }
        - { src: "backend.env.j2", dest: "backend.env" }
        - { src: "database.env.j2", dest: "database.env" }
        - { src: "pgadmin.env.j2", dest: "pgadmin.env" }

    - name: Copy compose + nginx
      copy:
        src: "../{{ item.src }}"
        dest: "{{ project_root }}/{{ item.dest }}"
      loop:
        - {
            src: "docker-compose-{{ env_type }}.yml",
            dest: "docker-compose.yml",
          }
        - { src: "nginx-{{ env_type }}.conf", dest: "nginx.conf" }

    - name: Check initialization marker
      stat:
        path: "{{ project_root }}/.initialized"
      register: init_file

    - name: Set deploy mode (init or update)
      set_fact:
        deploy_mode: "{{ deploy_mode if (deploy_mode is defined and deploy_mode in ['init', 'update']) else ('init' if not init_file.stat.exists else 'update') }}"

    - name: Docker login
      docker_login:
        username: "{{ dockerhub_user }}"
        password: "{{ dockerhub_token }}"

    - name: INIT - full deploy
      shell: docker compose up -d
      args:
        chdir: "{{ project_root }}"
      when: deploy_mode == "init"

    - name: Create initialization marker
      file:
        path: "{{ project_root }}/.initialized"
        state: touch
      when: deploy_mode == "init"

    - name: UPDATE - deploy service only
      shell: |
        docker compose pull {{ service_name }}
        docker compose up -d --no-deps --force-recreate {{ service_name }}
      args:
        chdir: "{{ project_root }}"
      when: deploy_mode == "update"

    - name: Update Celery
      shell: docker compose up -d --no-deps --force-recreate celery_worker celery_beat
      args:
        chdir: "{{ project_root }}"
      when:
        - service_name == "backend"
        - deploy_mode == "update"
