[staging]
host_staging ansible_host=44.219.245.214

[development]
host_development ansible_host=3.238.77.57

[servers:children]
staging
development

[all:vars]
ansible_user=wdoc_ansible_user
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
