- name: Server Provisioning
  hosts: servers
  become: yes

  vars:
    project_root: "/home/{{ ansible_user }}/app"
    env_type: "{{ env_type | default('development') }}"
    enable_ssl: "{{ enable_ssl | default(true) }}"
    site_domain: "{{ site_domain | default('') }}"
    origin_domain: "{{ origin_domain | default('') }}"

  roles:
    - role: server_tuning
    - role: host_setup
    - role: provision_ssl
