name: deploy

on:
    repository_dispatch:
        types: [trigger-deploy]

    workflow_dispatch:
        inputs:
            environment:
                required: true
                type: choice
                options: [development, staging]

            service:
                required: true
                type: choice
                options: [frontend, backend]

            deploy_mode:
                required: false
                default: update
                type: choice
                options: [init, update]

permissions:
    contents: read
    actions: write

jobs:
    terraform-check:
        uses: ./.github/workflows/terraform-check.yml
        secrets: inherit

    deploy:
        needs: terraform-check
        runs-on: ubuntu-latest
        environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.event.client_payload.ref == 'main' && 'staging' || 'development') }}

        env:
            ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch'
                && github.event.inputs.environment
                || (github.event.client_payload.ref == 'main' && 'staging' || 'development') }}

            SERVICE: ${{ github.event_name == 'workflow_dispatch'
                && github.event.inputs.service
                || github.event.client_payload.service }}

            DEPLOY_MODE: ${{ github.event_name == 'workflow_dispatch'
                && github.event.inputs.deploy_mode
                || github.event.client_payload.deploy_mode || 'update' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.ref || github.ref_name }}

            - name: Run Ansible Playbook
              uses: dawidd6/action-ansible-playbook@v2
              with:
                  playbook: ansible/deploy.yml
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  inventory: ansible/inventory.ini
                  options: >
                      --limit ${{ env.ENVIRONMENT }}
                      --extra-vars "
                      env_type=${{ env.ENVIRONMENT }}
                      service_name=${{ env.SERVICE }}
                      deploy_mode=${{ env.DEPLOY_MODE }}
                      domain_name=${{ env.ENVIRONMENT == 'staging' && 'staging.mydomain.com' || 'dev.mydomain.com' }}
                      dockerhub_user=${{ secrets.DOCKERHUB_USERNAME }}
                      dockerhub_token=${{ secrets.DOCKERHUB_TOKEN }}
                      db_name=${{ secrets.DB_NAME }}
                      db_user=${{ secrets.DB_USER }}
                      db_pass=${{ secrets.DB_PASSWORD }}
                      secret_key=${{ secrets.BACKEND_SECRET_KEY }}
                      api_url=${{ secrets.API_URL }}
                      allowed_hosts=${{ secrets.ALLOWED_HOSTS }}
                      pgadmin_email=${{ secrets.PGADMIN_EMAIL }}
                      pgadmin_pass=${{ secrets.PGADMIN_PASSWORD }}
                      "
