name: deploy

on:
    repository_dispatch:
        types: [trigger-deploy]
    workflow_dispatch:
        inputs:
            environment:
                required: true
                type: choice
                options: [development, staging]
            service:
                required: true
                type: choice
                options: [all, frontend, backend]

env:
    ENVIRONMENT: >-
        ${{ github.event_name == 'workflow_dispatch' &&
        github.event.inputs.environment ||  (github.event.client_payload.ref ==
        'main' && 'staging' || 'development') }}
    SERVICE: ${{ github.event.inputs.service || github.event.client_payload.service }}

concurrency:
    group: deploy-${{ github.event_name == 'workflow_dispatch' &&
        github.event.inputs.environment || (github.event.client_payload.ref ==
        'main' && 'staging' || 'development') }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    terraform-check:
        runs-on: ubuntu-latest
        environment: >-
            ${{ github.event_name == 'workflow_dispatch' &&
            github.event.inputs.environment ||  (github.event.client_payload.ref
            == 'main' && 'staging' || 'development') }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: IaC Security Scan
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "config"
                  severity: "CRITICAL"
                  exit-code: 1
                  scan-ref: "terraform/environments/${{ env.ENVIRONMENT }}"

    deploy:
        needs: terraform-check
        runs-on: ubuntu-latest
        environment: >-
            ${{ github.event_name == 'workflow_dispatch' &&
            github.event.inputs.environment ||  (github.event.client_payload.ref
            == 'main' && 'staging' || 'development') }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Run Ansible Playbook
              uses: dawidd6/action-ansible-playbook@v2
              with:
                  playbook: ansible/deploy.yml
                  key: |
                      ${{ secrets.SSH_PRIVATE_KEY }}
                  inventory: ""
                  options: >-
                      --limit ${{ env.ENVIRONMENT }}  --extra-vars "{
                          \"env_type\": \"${{ env.ENVIRONMENT || 'development' }}\",
                          \"service_name\": \"${{ env.SERVICE || 'all' }}\",
                          \"debug\": \"${{ env.ENVIRONMENT == 'development' && 'True' || 'False' }}\",

                          \"dockerhub_user\": \"${{ vars.DOCKERHUB_USERNAME || 'example_user' }}\",
                          \"email_host\": \"${{ vars.EMAIL_HOST || 'smtp.example.com' }}\",
                          \"email_port\": \"${{ vars.EMAIL_PORT || '587' }}\",
                          \"email_use_tls\": \"${{ vars.EMAIL_USE_TLS || 'true' }}\",
                          \"default_from_email\": \"${{ vars.DEFAULT_FROM_EMAIL || 'noreply@example.com' }}\",
                          \"use_s3\": \"${{ vars.USE_S3 || 'false' }}\",
                          \"aws_storage_bucket_name\": \"${{ vars.AWS_STORAGE_BUCKET_NAME || 'my-bucket' }}\",
                          \"aws_s3_region_name\": \"${{ vars.AWS_S3_REGION_NAME || 'us-east-1' }}\",
                          \"site_domain\": \"${{ vars.SITE_DOMAIN || 'example.com' }}\",
                          \"admin_email\": \"${{ vars.ADMIN_EMAIL || 'admin@example.com' }}\",

                          \"secret_key\": \"${{ secrets.SECRET_KEY || 'change-me-secret' }}\",
                          \"postgres_db\": \"${{ secrets.POSTGRES_DB || 'postgres' }}\",
                          \"postgres_user\": \"${{ secrets.POSTGRES_USER || 'postgres' }}\",
                          \"postgres_password\": \"${{ secrets.POSTGRES_PASSWORD || 'postgres' }}\",
                          \"postgres_host\": \"${{ secrets.POSTGRES_HOST || 'localhost' }}\",
                          \"celery_broker_url\": \"${{ secrets.CELERY_BROKER_URL || 'redis://redis:6379/0' }}\",
                          \"celery_result_backend\": \"${{ secrets.CELERY_RESULT_BACKEND || 'redis://redis:6379/1' }}\",
                          \"email_host_user\": \"${{ secrets.EMAIL_HOST_USER || 'user@example.com' }}\",
                          \"email_host_password\": \"${{ secrets.EMAIL_HOST_PASSWORD || 'password' }}\",
                          \"aws_access_key_id\": \"${{ secrets.AWS_ACCESS_KEY_ID || '' }}\",
                          \"aws_secret_access_key\": \"${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}\",
                          \"admin_username\": \"${{ secrets.ADMIN_USERNAME || 'admin' }}\",
                          \"admin_password\": \"${{ secrets.ADMIN_PASSWORD || 'admin' }}\",
                          \"grafana_password\": \"${{ secrets.GRAFANA_PASSWORD || 'grafana' }}\",
                          \"slack_webhook_url\": \"${{ secrets.SLACK_WEBHOOK_URL || '' }}\"
                      }"
