name: terraform-check

on:
    workflow_call:
        secrets:
            MY_GITHUB_TOKEN:
                required: false
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true

jobs:
    terraform-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "latest"

            - name: IaC Security Scan
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "config"
                  hide-progress: false
                  format: "table"
                  exit-code: "1"
                  severity: "CRITICAL,HIGH"

            - name: Terraform Format Check
              run: terraform fmt -check -recursive

            - name: Terraform Init
              run: terraform init
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Auto-fix
              run: terraform apply -auto-approve
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
